services:
  # RentEase API service
  api:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
      - ./web:/var/www/html/web
      - ./database:/var/www/database
