version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../api:/var/www/html
      - ../database:/var/www/database
    environment:
      - SQLITE_DATABASE=/var/www/database/rentease.db
